services:
  accounts:
    image: "786306/accounts:s4"
    container_name: accounts-ms
    ports:
     - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
     - eazybanks
networks:
  eazybanks:
    driver: "bridge"